### PR TITLE
fix: remove keyboard listerners and mark as unsupported

### LINKED ISSUE #6: Mark `Keyboard` module as unsupported on VisionOS
### Description

Goal of this issue is to mark `Keyboard` module as unsupported for VisionOS. 

As stated in Apple docs: https://developer.apple.com/documentation/uikit/uikeyboardwillshownotification?language=objc : 

> An app running in visionOS never receives this notification. The system displays the keyboard in a separate window, leaving the app’s window unaffected by the keyboard’s appearance and disappearance.

Goals: 
- Avoid registering listeners inside `RCTKeyboardObserver` (`#if TARGET_OS_VISION`)
- Mark `Keyboard` and `KeyboardAvoidingView` as not supported

### PR DESCRIPTION
**Pull request by thiagobrez**
## Summary:

Fixes #6 

Mark `Keyboard.js` and `KeyboardAvoidingView.js` as unsupported and remove listeners in `RCTKeyboardObserver.mm`, because VisionOS displays the keyboard in a separate window, leaving the app window unaffected.

## Changelog:

[VISIONOS] [ADDED] - warning about unavailable Keyboard
[VISIONOS] [ADDED] - warning about unavailable KeyboardAvoidingView
[VISIONOS] [CHANGED] - early return when adding and removing listeners in Keyboard
[VISIONOS] [CHANGED] - return passthrough View when rendering KeyboardAvoidingView on VisionOS
[VISIONOS] [CHANGED] - do nothing if TARGET_OS_VISION in `startObserving` and `stopObserving`

## Test Plan:

1. Open KeyboardAvoidingView in RNTester
2. Verify warn is displayed in the app and in the Metro logs
3. Verify examples should still load and function correctly

### CODE REVIEW

File: packages/react-native/Libraries/Components/Keyboard/Keyboard.js [hunk 1]
```diff
@@ -114,6 +114,13 @@ class Keyboard {
     );
 
   constructor() {
+    if (Platform.isVisionOS) {
```
Comment (matthargett) [inline packages/react-native/Libraries/Components/Keyboard/Keyboard.js:117]: Can we not create Keyboard.visionOS.js and have it return a noop or throw upon require? It seems like these `if` should be pulled into the Tester app itself, which is what I could expect in end-user app logic as well. If a visionOS app requires this file, and tries to use any methods, the developer probably isn't understanding the platform correctly.

Comment (okwasniewski) [reply packages/react-native/Libraries/Components/Keyboard/Keyboard.js:117]: It could be a possible solution but I think it's a nice DX to have instructions that this module is not supported on this platform. 

We can wait with merging of this PR till I will implement the Platform.OS (for visionOS) and make it a noop file.

Comment (satya164) [reply packages/react-native/Libraries/Components/Keyboard/Keyboard.js:117]: wouldn't the warning be annoying when writing cross platform apps?

Comment (thiagobrez) [reply packages/react-native/Libraries/Components/Keyboard/Keyboard.js:117]: Agree, if we have the `.visionOS` platform file, would also vote for removing warnings

Comment (okwasniewski) [reply packages/react-native/Libraries/Components/Keyboard/Keyboard.js:117]: There is also way to `warnOnce` as @satya164 said constant warning might be annoying. Looks like react-native-tvos is following this pattern: 

image

**Comment by okwasniewski** [comment]
Hey! @thiagobrez 

It would be great if you could rebase your PR and change calls to `console.warn` to warnOnce like in Tomek's PR here: https://github.com/callstack/react-native-visionos/pull/24

**Comment by thiagobrez** [comment]
Sorry for the delay @okwasniewski , I thought we were waiting on https://github.com/callstack/react-native-visionos/issues/20. Should be good now

**Comment by okwasniewski** [comment]
Thanks for this!
